### ISSUE TITLE
Issue with environments and calculation of Molecular Fingerprints

### ISSUE THREAD

**Issue by thewhovianwho** [vibudh2209/D2#11]
Hello,

I think a thorough tutorial would be really nice. Maybe some example output for all the stages, including the preparing molecules stage. I tried to get the molecular fingerprints for 5 .smi files, the folder is created but I only get a value printed in the terminal. 
There is a problem with the environments: when both, conda and virtualenv, are active, rdkit can't pe imported. Deactivating virtualenv does the trick, though. My question is: are 2 environments necessary? Why can't I install the requirements just on the conda environment, for example?

Thank you!

**Comment by fgentile89** [comment]
Hi,
a tutorial is indeed in our to-do-list. 
Could you be more specific on the problem you see with calculating morgan fingerprint?
Regarding the environment, you need two of them to avoid conflicts between tensorflow versions. To calculate the morgan fingerprint you just need to activate the rdkit environment, activating virtualenv on the top of that will overwrite the modules to be imported and rdkit will not be there.
