### ISSUE TITLE
simple_job_predictions_noslurm

### ISSUE THREAD

**Issue by albertma-evotec** [vibudh2209/D2#16]
I am at Phase 5, step 2 running the python simple_job_predictions_noslurm.py script. It is the first iteration.
It returns the following error. 
`Traceback (most recent call last):
  File "simple_job_predictions_noslurm.py", line 63, in <module>
    ref.write('cd '+pd_folder_path+'\n')
NameError: name 'pd_folder_path' is not defined
`
When I look at the code in the python file, line 63 and 64
`        ref.write('cd '+pd_folder_path+'\n')`
`        ref.write('source '+tf_venv_path+'/bin/activate\n')`

pd_folder_path and tf_venv_path are not defined anywhere. 

Is it supposed to be have these two arguments in the file just like simple_job_models_noslurm.py does?
`parser.add_argument('-pdfp','--pd_folder_path',required=True)`
`parser.add_argument('-tfp','--tf_venv_path',required=True)`

**Comment by fgentile89** [comment]
Yes you're right. Somehow those lines were left out of simple_job_predictions_noslurm.py. This has been corrected now, and the readme has been updated with the right, complete command. Let me know if you encounter any other issue
